import { CampaignPreset, SocialComment } from '../types';

export const initialComments: SocialComment[] = [
  {
    id: 'c-101',
    platform: 'tiktok',
    author: 'sofia_creative',
    authorHandle: '@sofia_creative',
    authorAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&auto=format&fit=crop&q=80',
    isVerified: true,
    content: '¡Me llegó hoy y superó por completo mis expectativas! La calidad del empaque y la rapidez fueron brutales 🔥🤩 #inlove',
    timestamp: 'Hace 12 min',
    likes: 1420,
    repliesCount: 45,
    postUrl: 'https://www.tiktok.com/@brand/video/7391823901',
    postTitle: 'Unboxing oficial nueva edición 2026',
    sentiment: 'positive',
    sentimentScore: 0.92,
    primaryEmotion: 'joy',
    emotionalIntensity: 9,
    keywords: ['calidad', 'empaque', 'rapidez', 'inlove'],
    category: 'Experiencia de Producto',
    isSarcastic: false,
    suggestedReply: '¡Qué emoción Sofía! Nos alegra muchísimo que te haya encantado. ¡Que lo disfrutes al máximo! ✨❤️',
    reasoning: 'Entusiasmo genuino y confirmación de alta calidad del producto con léxico hiperpositivo.',
    starred: true,
    userTags: ['influencer', 'unboxing'],
  },
  {
    id: 'c-102',
    platform: 'instagram',
    author: 'carlos_techdev',
    authorHandle: '@carlos_techdev',
    authorAvatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=100&auto=format&fit=crop&q=80',
    isVerified: false,
    content: 'El diseño es hermoso pero llevo 4 días esperando respuesta del soporte para el número de guía... por favor respondan el DM 🙄',
    timestamp: 'Hace 35 min',
    likes: 312,
    repliesCount: 18,
    postUrl: 'https://www.instagram.com/p/C98xZ1029/',
    postTitle: 'Disponible en todos los países de Latam',
    sentiment: 'negative',
    sentimentScore: -0.65,
    primaryEmotion: 'frustration',
    emotionalIntensity: 7,
    keywords: ['soporte', 'guía', 'esperando', 'dm'],
    category: 'Atención al Cliente',
    isSarcastic: false,
    suggestedReply: 'Hola Carlos, te pedimos una disculpa sincera por la demora. Ya te acabamos de responder por mensaje privado para verificar tu guía de inmediato.',
    reasoning: 'Frustración causada por demora en el servicio de soporte postventa a pesar de elogiar el diseño.',
    starred: false,
    userTags: ['soporte-urgente'],
  },
  {
    id: 'c-103',
    platform: 'facebook',
    author: 'Maria Elena Gomez',
    authorHandle: '@maria.elena.gomez',
    authorAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&auto=format&fit=crop&q=80',
    isVerified: false,
    content: '¿Tienen sucursales en Bogotá o realizan envíos con pago contra entrega? Me interesa comprar dos unidades para regalo familiar.',
    timestamp: 'Hace 1 hora',
    likes: 45,
    repliesCount: 4,
    postUrl: 'https://facebook.com/brand/posts/891238472',
    postTitle: 'Lanzamiento oficial de temporada',
    sentiment: 'neutral',
    sentimentScore: 0.15,
    primaryEmotion: 'curiosity',
    emotionalIntensity: 4,
    keywords: ['bogota', 'pago contra entrega', 'comprar', 'regalo'],
    category: 'Intención de Compra',
    isSarcastic: false,
    suggestedReply: '¡Hola María Elena! Sí tenemos cobertura en toda Bogotá con opción de pago contra entrega. Puedes hacer tu pedido directo en el enlace de nuestra biografía.',
    reasoning: 'Consulta comercial con alta intención de compra sin carga emocional negativa.',
    starred: true,
    userTags: ['lead-caliente'],
  },
  {
    id: 'c-104',
    platform: 'tiktok',
    author: 'valen_trends',
    authorHandle: '@valen_trends',
    authorAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=100&auto=format&fit=crop&q=80',
    isVerified: true,
    content: 'Todo TikTok hablando de esto jajaja ya me convencieron, lo acabo de pedir 💸 si no me queda como en el video lloro',
    timestamp: 'Hace 2 horas',
    likes: 3890,
    repliesCount: 89,
    postUrl: 'https://www.tiktok.com/@brand/video/7391823901',
    postTitle: 'Tendencia viral #GlowUpChallenge',
    sentiment: 'positive',
    sentimentScore: 0.78,
    primaryEmotion: 'joy',
    emotionalIntensity: 8,
    keywords: ['tiktok', 'viral', 'pedir', 'glowup'],
    category: 'Prueba Social y Viralidad',
    isSarcastic: false,
    suggestedReply: '¡Jajaja te va a quedar incluso mejor Valen! Etiquétanos en tu video cuando te llegue para compartirlo 🤩',
    reasoning: 'Comentario con humor y validación social positiva con compra confirmada.',
    starred: false,
    userTags: ['viral'],
  },
  {
    id: 'c-105',
    platform: 'instagram',
    author: 'mateo_estilo',
    authorHandle: '@mateo_estilo',
    authorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80',
    isVerified: false,
    content: 'Excelente que saquen opciones sostenibles, pero 120 dólares por una camiseta básica me parece una locura total para el mercado latino.',
    timestamp: 'Hace 3 horas',
    likes: 856,
    repliesCount: 42,
    postUrl: 'https://www.instagram.com/p/C98xZ1029/',
    postTitle: 'Colección Orgánica y Sostenible 2026',
    sentiment: 'mixed',
    sentimentScore: -0.2,
    primaryEmotion: 'skepticism',
    emotionalIntensity: 6,
    keywords: ['precio', 'sostenible', 'costoso', 'dolares'],
    category: 'Precios y Valor',
    isSarcastic: false,
    suggestedReply: 'Hola Mateo, entendemos tu punto. Nuestros materiales tienen certificación internacional de comercio justo y huella de carbono neutra, pero tomamos muy en cuenta tu opinión.',
    reasoning: 'Reconocimiento del mérito ecológico pero objeción fuerte respecto al precio elevado.',
    starred: false,
    userTags: ['precio-feedback'],
  },
  {
    id: 'c-106',
    platform: 'facebook',
    author: 'Rodrigo Santoro Diaz',
    authorHandle: '@rodrigo.santoro.oficial',
    authorAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&auto=format&fit=crop&q=80',
    isVerified: false,
    content: 'Pesima atencion! El paquete llego roto y no me dan solucion por correo desde hace una semana. Voy a poner la queja en proteccion al consumidor.',
    timestamp: 'Hace 4 horas',
    likes: 128,
    repliesCount: 15,
    postUrl: 'https://facebook.com/brand/posts/891238472',
    postTitle: 'Envíos a todo el país',
    sentiment: 'negative',
    sentimentScore: -0.92,
    primaryEmotion: 'anger',
    emotionalIntensity: 10,
    keywords: ['pesima atencion', 'roto', 'queja', 'consumidor'],
    category: 'Incidencias Críticas y Envíos',
    isSarcastic: false,
    suggestedReply: 'Rodrigo, lamentamos profundamente este incidente inaceptable. Nuestro gerente de servicio al cliente te contactará telefónicamente en menos de 30 minutos para gestionar el reemplazo y compensación.',
    reasoning: 'Molestia extrema por daño en el producto y falta de respuesta oportuna.',
    starred: true,
    userTags: ['urgente-riesgo-legal'],
  },
  {
    id: 'c-107',
    platform: 'tiktok',
    author: 'camila_dance',
    authorHandle: '@camila_dance',
    authorAvatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=100&auto=format&fit=crop&q=80',
    isVerified: false,
    content: 'El color en persona es 10 veces más lindo que en las fotos!! Hagan más colores pasteles por favorrr 🌸 pastel lavender seria un éxito',
    timestamp: 'Hace 5 horas',
    likes: 940,
    repliesCount: 23,
    postUrl: 'https://www.tiktok.com/@brand/video/7391823901',
    postTitle: 'Detalle de texturas y colores',
    sentiment: 'positive',
    sentimentScore: 0.88,
    primaryEmotion: 'love',
    emotionalIntensity: 8,
    keywords: ['color', 'pasteles', 'lindo', 'lavender'],
    category: 'Feedback de Producto',
    isSarcastic: false,
    suggestedReply: '¡Anotadísimo Camila! 🌸 Nos encanta la idea del lavender pastel, se lo pasamos directo a nuestro equipo de diseño.',
    reasoning: 'Elogio estético muy alto y sugerencia constructiva de nuevos tonos.',
    starred: false,
    userTags: ['peticion-producto'],
  },
  {
    id: 'c-108',
    platform: 'facebook',
    author: 'Gabriela Mendez',
    authorHandle: '@gabriela.mendez.33',
    authorAvatar: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=100&auto=format&fit=crop&q=80',
    isVerified: false,
    content: 'Super útil la actualización de la app, ahora es mucho más fácil ver el tracking del pedido en tiempo real. 10 de 10!',
    timestamp: 'Hace 6 horas',
    likes: 67,
    repliesCount: 3,
    postUrl: 'https://facebook.com/brand/posts/891238472',
    postTitle: 'Nueva versión de nuestra aplicación móvil',
    sentiment: 'positive',
    sentimentScore: 0.85,
    primaryEmotion: 'joy',
    emotionalIntensity: 7,
    keywords: ['app', 'tracking', 'util', 'tiempo real'],
    category: 'Tecnología y App',
    isSarcastic: false,
    suggestedReply: '¡Qué gran noticia Gabriela! Nos esforzamos mucho por renovar el sistema de tracking para que tengan total tranquilidad. ¡Gracias por confiar en nosotros! 🚀',
    reasoning: 'Aprobación entusiasta del nuevo módulo de rastreo.',
    starred: false,
    userTags: ['app-feedback'],
  },
  {
    id: 'c-109',
    platform: 'instagram',
    author: 'sarcastic_critic',
    authorHandle: '@sarcastic_critic',
    authorAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&auto=format&fit=crop&q=80',
    isVerified: false,
    content: 'Claaaro, "envío gratis en 24 horas"... si las 24 horas duran dos semanas enteras jajaja un aplauso 👏😂',
    timestamp: 'Hace 7 horas',
    likes: 642,
    repliesCount: 38,
    postUrl: 'https://www.instagram.com/p/C98xZ1029/',
    postTitle: 'Envíos express en 24h',
    sentiment: 'negative',
    sentimentScore: -0.75,
    primaryEmotion: 'sarcasm',
    emotionalIntensity: 8,
    keywords: ['envio gratis', 'retraso', 'sarcasmo', 'espera'],
    category: 'Logística y Tiempos',
    isSarcastic: true,
    suggestedReply: 'Entendemos la ironía y tienes toda la razón en exigir puntualidad. Si tu paquete sufrió retrasos, déjanos tu número de orden por DM para investigarlo ya mismo.',
    reasoning: 'Uso explícito de ironía y sarcasmo para criticar el incumplimiento de tiempos prometidos.',
    starred: true,
    userTags: ['sarcasmo-detectado'],
  },
  {
    id: 'c-110',
    platform: 'tiktok',
    author: 'dani_fitness',
    authorHandle: '@dani_fitness',
    authorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80',
    isVerified: true,
    content: '¿Viene con garantía de fábrica? Me gustaría saber qué cubre en caso de fallas técnicas en los primeros meses.',
    timestamp: 'Hace 8 horas',
    likes: 180,
    repliesCount: 9,
    postUrl: 'https://www.tiktok.com/@brand/video/7391823901',
    postTitle: 'Rendimiento y resistencia garantizada',
    sentiment: 'neutral',
    sentimentScore: 0.05,
    primaryEmotion: 'curiosity',
    emotionalIntensity: 4,
    keywords: ['garantia', 'fallas tecnicas', 'cobertura'],
    category: 'Garantía y Políticas',
    isSarcastic: false,
    suggestedReply: '¡Hola Dani! Cuenta con 12 meses de garantía directa contra cualquier defecto de fábrica o fallo técnico. Si gustas te enviamos la póliza detallada.',
    reasoning: 'Pregunta formal sobre políticas de garantía sin carga emocional extrema.',
    starred: false,
    userTags: ['garantia'],
  },
  {
    id: 'c-111',
    platform: 'instagram',
    author: 'lucia_wellness',
    authorHandle: '@lucia_wellness',
    authorAvatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=100&auto=format&fit=crop&q=80',
    isVerified: true,
    content: 'Totalmente recomendado. Ya es el tercer producto que compro este año y la durabilidad es insuperable. Vale cada centavo! 💯',
    timestamp: 'Hace 9 horas',
    likes: 1250,
    repliesCount: 19,
    postUrl: 'https://www.instagram.com/p/C98xZ1029/',
    postTitle: 'Historias de clientes fieles',
    sentiment: 'positive',
    sentimentScore: 0.94,
    primaryEmotion: 'love',
    emotionalIntensity: 9,
    keywords: ['recomendado', 'durabilidad', 'calidad', 'fidelidad'],
    category: 'Fidelización de Clientes',
    isSarcastic: false,
    suggestedReply: '¡Lucia, qué honor contar con clientes como tú! Gracias inmensas por tu confianza continua. Te enviamos un regalo especial a tu correo 🎁✨',
    reasoning: 'Cliente recurrente con testimonio de lealtad y máxima puntuación de satisfacción.',
    starred: true,
    userTags: ['cliente-vip'],
  },
  {
    id: 'c-112',
    platform: 'facebook',
    author: 'Hernan Pizarro',
    authorHandle: '@hernan.pizarro',
    authorAvatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=100&auto=format&fit=crop&q=80',
    isVerified: false,
    content: 'La página de pago se queda cargando en un bucle infinito al intentar pagar con tarjeta Mastercard. ¿A alguien más le pasa?',
    timestamp: 'Hace 10 horas',
    likes: 89,
    repliesCount: 22,
    postUrl: 'https://facebook.com/brand/posts/891238472',
    postTitle: 'Descuentos exclusivos de fin de semana',
    sentiment: 'negative',
    sentimentScore: -0.58,
    primaryEmotion: 'frustration',
    emotionalIntensity: 6,
    keywords: ['bucle', 'pasarela de pago', 'error', 'mastercard'],
    category: 'Plataforma y Checkout',
    isSarcastic: false,
    suggestedReply: 'Hernan, gracias por reportarlo. Nuestro equipo técnico acaba de reiniciar la pasarela bancaria. Ya puedes recargar la página o probar por el enlace alternativo.',
    reasoning: 'Reporte de bug técnico que bloquea la conversión de compras.',
    starred: true,
    userTags: ['bug-checkout', 'urgente'],
  }
];

export const campaignPresets: CampaignPreset[] = [
  {
    id: 'tech-gadget',
    title: 'Lanzamiento Smartphone Nova Pro 2026',
    description: 'Comentarios de TikTok, Reels y Facebook con unboxing, debates sobre precio, batería y envíos.',
    platform: 'all',
    category: 'Tecnología & Gadgets',
    comments: initialComments,
  },
  {
    id: 'viral-fashion',
    title: 'Colección Viral Streetwear TikTok Haul',
    description: 'Comentarios de alta viralidad con opiniones sobre estética, tallas, telas sostenibles y peticiones de colores.',
    platform: 'tiktok',
    category: 'Moda y Lifestyle',
    comments: [
      {
        id: 'vf-1',
        platform: 'tiktok',
        author: 'chloe_fits',
        authorHandle: '@chloe_fits',
        authorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80',
        content: 'La tela es súper suave y el corte oversize queda perfecto! Necesito esto en tono moca ya mismo 🤎',
        timestamp: 'Hace 15 min',
        likes: 2450,
        sentiment: 'positive',
        sentimentScore: 0.9,
        primaryEmotion: 'joy',
        keywords: ['tela', 'oversize', 'suave', 'moca'],
        category: 'Calidad y Ajuste',
        starred: true,
      },
      {
        id: 'vf-2',
        platform: 'tiktok',
        author: 'alexitto_style',
        authorHandle: '@alexitto_style',
        authorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80',
        content: 'Ojo con las tallas! Pedí M y parece XL gigante, van a tener que cambiar la tabla de medidas.',
        timestamp: 'Hace 45 min',
        likes: 820,
        sentiment: 'negative',
        sentimentScore: -0.55,
        primaryEmotion: 'frustration',
        keywords: ['tallas', 'medidas', 'cambio'],
        category: 'Guía de Tallas',
        starred: false,
      },
      {
        id: 'vf-3',
        platform: 'tiktok',
        author: 'mimi_aesthetic',
        authorHandle: '@mimi_aesthetic',
        authorAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=100&auto=format&fit=crop&q=80',
        content: 'Hagan restock de la chaqueta de cuero vegano por favor, se agotó en 2 minutos literales 😭',
        timestamp: 'Hace 1 hora',
        likes: 1930,
        sentiment: 'positive',
        sentimentScore: 0.65,
        primaryEmotion: 'curiosity',
        keywords: ['restock', 'agotado', 'cuero vegano'],
        category: 'Demanda de Stock',
        starred: true,
      },
      {
        id: 'vf-4',
        platform: 'tiktok',
        author: 'fashion_realist',
        authorHandle: '@fashion_realist',
        authorAvatar: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=100&auto=format&fit=crop&q=80',
        content: 'El marketing es 10/10 pero las costuras internas vinieron un poco deshilachadas para el precio que tiene.',
        timestamp: 'Hace 2 horas',
        likes: 410,
        sentiment: 'mixed',
        sentimentScore: -0.3,
        primaryEmotion: 'skepticism',
        keywords: ['costuras', 'precio', 'calidad'],
        category: 'Control de Calidad',
        starred: false,
      }
    ],
  },
  {
    id: 'food-delivery',
    title: 'Campaña Smash Burger Gourmet',
    description: 'Opiniones gastronómicas de Instagram y Facebook: sabor, tiempo de entrega, packaging térmico y precios.',
    platform: 'instagram',
    category: 'Restaurantes & Alimentos',
    comments: [
      {
        id: 'fd-1',
        platform: 'instagram',
        author: 'foodie_bogota',
        authorHandle: '@foodie_bogota',
        authorAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&auto=format&fit=crop&q=80',
        content: 'El pan brioche y la carne crujiente en los bordes es un espectáculo total! 🍔🤤 La salsa especial es adictiva.',
        timestamp: 'Hace 20 min',
        likes: 1840,
        sentiment: 'positive',
        sentimentScore: 0.95,
        primaryEmotion: 'love',
        keywords: ['pan brioche', 'salsa especial', 'espectaculo'],
        category: 'Experiencia Gastronómica',
        starred: true,
      },
      {
        id: 'fd-2',
        platform: 'instagram',
        author: 'javier_gourmet',
        authorHandle: '@javier_gourmet',
        authorAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&auto=format&fit=crop&q=80',
        content: 'El pedido tardó 1 hora y 20 minutos en llegar un martes en la noche y las papas llegaron frías 🍟👎',
        timestamp: 'Hace 50 min',
        likes: 310,
        sentiment: 'negative',
        sentimentScore: -0.85,
        primaryEmotion: 'anger',
        keywords: ['demora', 'papas frias', 'entrega'],
        category: 'Tiempos de Entrega',
        starred: true,
      },
      {
        id: 'fd-3',
        platform: 'facebook',
        author: 'Carolina Restrepo',
        authorHandle: '@caro.restrepo',
        authorAvatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=100&auto=format&fit=crop&q=80',
        content: '¿Tienen opciones vegetarianas o burger con hongos portobello? Mis amigos quieren ir el viernes.',
        timestamp: 'Hace 3 horas',
        likes: 88,
        sentiment: 'neutral',
        sentimentScore: 0.2,
        primaryEmotion: 'curiosity',
        keywords: ['vegetariana', 'portobello', 'menu'],
        category: 'Variedad de Menú',
        starred: false,
      }
    ]
  }
];

export const sampleLiveFeedPool: Array<Omit<SocialComment, 'id' | 'timestamp'>> = [
  {
    platform: 'tiktok',
    author: 'lucas_stream',
    authorHandle: '@lucas_stream',
    authorAvatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=100&auto=format&fit=crop&q=80',
    content: '¡Acabo de probarlo en vivo y la fluidez es impresionante! Super recomendado para creadores de contenido 🚀',
    likes: 54,
    sentiment: 'positive',
    sentimentScore: 0.88,
    primaryEmotion: 'joy',
    emotionalIntensity: 8,
    keywords: ['fluidez', 'creadores', 'recomendado'],
    category: 'Desempeño',
  },
  {
    platform: 'instagram',
    author: 'mariana_photos',
    authorHandle: '@mariana_photos',
    authorAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&auto=format&fit=crop&q=80',
    content: '¿Cuándo tendrán stock nuevamente en México? Intenté comprar y salía agotado en la web.',
    likes: 19,
    sentiment: 'neutral',
    sentimentScore: 0.1,
    primaryEmotion: 'curiosity',
    emotionalIntensity: 3,
    keywords: ['stock', 'mexico', 'agotado'],
    category: 'Disponibilidad',
  },
  {
    platform: 'facebook',
    author: 'Santiago Beltran',
    authorHandle: '@santi.beltran',
    authorAvatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=100&auto=format&fit=crop&q=80',
    content: 'No me parece justo que cobren tarifa adicional de envío si en el video dijeron que era gratis para todo el país.',
    likes: 72,
    sentiment: 'negative',
    sentimentScore: -0.68,
    primaryEmotion: 'frustration',
    emotionalIntensity: 7,
    keywords: ['costo envio', 'promocion', 'inconformidad'],
    category: 'Políticas de Envío',
  },
  {
    platform: 'tiktok',
    author: 'valen_vibes',
    authorHandle: '@valen_vibes',
    authorAvatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=100&auto=format&fit=crop&q=80',
    content: 'Me salvaron el regalo de aniversario! Llegó a tiempo y el envoltorio de regalo quedó hermoso ❤️✨',
    likes: 110,
    sentiment: 'positive',
    sentimentScore: 0.93,
    primaryEmotion: 'love',
    emotionalIntensity: 9,
    keywords: ['regalo', 'a tiempo', 'hermoso'],
    category: 'Servicio al Cliente',
  }
];
